# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v0.6.0-106-g72fc5db
_src_path: https://github.com/usnistgov/cookiecutter-nist-python.git
command_line_interface: argparse
conda_channel: wpk-nist
email: wpk@nist.gov
full_name: William P. Krekelberg
github_username: wpk-nist-gov
project_name: sync-pre-commit-hooks
project_short_description: Some useful pre-commit hooks dependencies, etc.
project_slug: sync_pre_commit_hooks
pypi_username: wpk-nist
sphinx_theme: sphinx_book_theme
sphinx_use_autodocsumm: true
year: '2025'
