- id: sync-pre-commit-deps
  name: sync-pre-commit-deps
  description: Sync pre-commit hook dependencies base on installed hooks
  entry: sync-pre-commit-deps
  language: python
  additional_dependencies:
    - ".[sync-pre-commit-deps]"
  files: ^\.pre-commit-config\.yaml$
  pass_filenames: false
  minimum_pre_commit_version: "2.9.2"
- id: sync-uv-dependency-groups
  name: sync-uv-dependency-groups
  description:
    Sync minimum python version in "tool.uv.dependency-groups" table of
    "pyproject.toml"
  entry: sync-uv-dependency-groups
  language: python
  additional_dependencies:
    - ".[sync-uv-dependency-groups]"
  files: ^pyproject\.toml$|^\.python-version$
  pass_filenames: false
  minimum_pre_commit_version: "2.9.2"
- id: apply-command
  name: apply-command
  description: Apply single file executable to multiple files
  entry: apply-command
  args: ["python -c 'print(0)'"]
  language: python
  pass_filenames: true
  minimum_pre_commit_version: "2.9.2"
- id: justfile-format
  name: justfile-format
  description: Format justfiles
  entry: apply-command
  args: [just, --fmt, --unstable, --justfile]
  language: python
  files: \.?[jJ]ustfile$|.*\.just$
  pass_filenames: true
  minimum_pre_commit_version: "2.9.2"
- id: fill-pre-commit-hook-deps
  name: fill-pre-commit-hook-deps
  description:
    Fill additions dependencies for hook from pyproject.toml or requirements.txt
  entry: fill-pre-commit-deps
  args: ["--help"]
  language: python
  additional_dependencies:
    - ".[fill-pre-commit-hook-deps]"
  pass_filenames: false
  minimum_pre_commit_version: "2.9.2"
